name: Build 
description: Build spring boot application
on:
  workflow_call:
    username: 
      description: 'username of the docker'
        required: true
    password: 
      description: 'password of the docker'
        required: true

outputs:
  image_name:
    description: The name of the built Docker image
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Maven
        shell: bash
        run: mvn clean install
      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        # shell: bash
        # run:
        #   echo "${{ secrets.docker_password }}" | docker login -u "${{ secrets.docker_username }}" --password-stdin

      - name: Build Docker Image
        shell: bash
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-petclinic .
          echo "image_name= ${{ secrets.DOCKER_USERNAME }}/spring-petclinic:latest" >> $GITHUB_ENV
        
      - name: Publish the docker image
        shell: bash
        run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-petclinic:latest 

    outputs:
    image_name: ${{ inputs.image_name }}
