name: Build 
description: Build spring boot application

outputs:
  image_name:
    description: The name of the built Docker image
runs:
  using: "composite"  
  steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Maven
      shell: bash
      run: mvn clean install
    - name: login to docker hub
      shell: bash
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run:
        echo "${{ inputs.DOCKER_PASSWORD }}" | docker login -u "${{ inputs.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker Image
      shell: bash
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/spring-petclinic .
        echo "image_name= ${{ secrets.DOCKER_USERNAME }}/spring-petclinic:latest" >> $GITHUB_ENV
        
    - name: Publish the docker image
      shell: bash
      run: docker push ${{ secrets.DOCKER_USERNAME }}/spring-petclinic:latest  
